### ISSUE TITLE
erros running on IARPA dataset

### ISSUE THREAD

**Issue by sebasmurphy** [cmla/s2p#51]
I'm trying to run your solution on the IARPA Explorer dateset. Everything runs fine with just a few images but once I increase the number of images the processes that get spawned start crashing. 

Has anyone else run into this issue.  The docker process is running on a 16 core machine with 40GB memory so I don't believe that it is a hardware issue.

config
```
{
  images:[25 images from the dataset]
  "roi": {
    "h": 1500.0,
    "w": 1500.0,
    "y": 14000,
    "x": 16000
  },
  "max_processes": 14,
  "debug": true,
  "full_img": false,
  "horizontal_margin": 20,
  "vertical_margin": 5,
  "tile_size": 1000,
  "disp_range_method": "sift",
  "msk_erosion": 0,
  "dsm_resolution": 0.5,
  "register_with_shear": true
}

```

```
RUN: ['plambda', '/bigdata/output/tiles/row_0014000_height_750/col_0016750_width_750/pair_22/rectified_disp.tif', '
/bigdata/output/tiles/row_0014000_height_750/col_0016750_width_750/pair_22/rectified_ref.tif', '/root/s2p/s2p_tmp/s
2p_r8u9295n.tif', 'x isfinite y isfinite z isfinite and and', '-o', '/bigdata/output/tiles/row_0014000_height_750/c
ol_0016750_width_750/pair_22/rectified_mask.png']
plambda correspondence "x" = "/bigdata/output/tiles/row_0014000_height_750/col_0016750_width_750/pair_22/rectified_
disp.tif"
plambda correspondence "y" = "/bigdata/output/tiles/row_0014000_height_750/col_0016750_width_750/pair_22/rectified_
ref.tif"
plambda correspondence "z" = "/root/s2p/s2p_tmp/s2p_r8u9295n.tif"
0:00:00.711253
12terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Exception in stereo_matching
Traceback (most recent call last):
  File "/root/s2p/s2p/parallel.py", line 43, in tilewise_wrapper
    out = fun(*args)
  File "/root/s2p/s2p/__init__.py", line 204, in stereo_matching
    max_disp_range=cfg['max_disp_range'])
  File "/root/s2p/s2p/block_matching.py", line 180, in compute_disparity_map
    timeout=timeout,
  File "/root/s2p/s2p/common.py", line 93, in run
    env=env, timeout=timeout, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['mgm', '-r', '-1007', '-R', '246', '-s', 'vfit', '-t', 'census', '-O', '8'
, '-confidence_consensusL', '/bigdata/output/tiles/row_0014750_height_750/col_0016000_width_750/pair_21/rectified_d
isp_confidence.tif', '/bigdata/output/tiles/row_0014750_height_750/col_0016000_width_750/pair_21/rectified_ref.tif'
, '/bigdata/output/tiles/row_0014750_height_750/col_0016000_width_750/pair_21/rectified_sec.tif', '/bigdata/output/
tiles/row_0014750_height_750/col_0016000_width_750/pair_21/rectified_disp.tif']' died with <Signals.SIGABRT: 6>.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/root/s2p/s2p/parallel.py", line 43, in tilewise_wrapper
    out = fun(*args)
  File "/root/s2p/s2p/__init__.py", line 204, in stereo_matching
    max_disp_range=cfg['max_disp_range'])
  File "/root/s2p/s2p/block_matching.py", line 180, in compute_disparity_map
    timeout=timeout,
  File "/root/s2p/s2p/common.py", line 93, in run
    env=env, timeout=timeout, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['mgm', '-r', '-1007', '-R', '246', '-s', 'vfit', '-t', 'census', '-O', '8'
, '-confidence_consensusL', '/bigdata/output/tiles/row_0014750_height_750/col_0016000_width_750/pair_21/rectified_d
isp_confidence.tif', '/bigdata/output/tiles/row_0014750_height_750/col_0016000_width_750/pair_21/rectified_ref.tif'
, '/bigdata/output/tiles/row_0014750_height_750/col_0016000_width_750/pair_21/rectified_sec.tif', '/bigdata/output/
tiles/row_0014750_height_750/col_0016000_width_750/pair_21/rectified_disp.tif']' died with <Signals.SIGABRT: 6>.
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/bin/s2p", line 11, in <module>
    load_entry_point('s2p', 'console_scripts', 's2p')()
  File "/root/s2p/s2p/cli.py", line 22, in main
    s2p.main(user_cfg)
  File "/root/s2p/s2p/__init__.py", line 614, in main
    timeout=timeout)
  File "/root/s2p/s2p/parallel.py", line 102, in launch_calls
    outputs.append(r.get(timeout))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
subprocess.CalledProcessError: Command '['mgm', '-r', '-1007', '-R', '246', '-s', 'vfit', '-t', 'census', '-O', '8'
, '-confidence_consensusL', '/bigdata/output/tiles/row_0014750_height_750/col_0016000_width_750/pair_21/rectified_d
isp_confidence.tif', '/bigdata/output/tiles/row_0014750_height_750/col_0016000_width_750/pair_21/rectified_ref.tif'
, '/bigdata/output/tiles/row_0014750_height_750/col_0016000_width_750/pair_21/rectified_sec.tif', '/bigdata/output/
tiles/row_0014750_height_750/col_0016000_width_750/pair_21/rectified_disp.tif']' died with <Signals.SIGABRT: 6>.
root@1f0b5028a89a:~/s2p# 34567
```

**Comment by carlodef** [comment]
Hi @sebasmurphy, `s2p` is meant mostly for pairs (2 images) or triplets (3 images) of stereo images. It accepts inputs with more than 3 images, but these should be single-pass multiview stereo datasets, such as for example the 6 WorldView-3 images of the IARPA dataset acquired on 18 December 2015. A single run with a set of 25 images collected at different dates is very likely to fail.

For the IARPA challenge, `s2p` was run 50 times on 50 different image pairs selected from the  dataset. More info here: https://gfacciol.github.io/multi-date-stereo/

**Comment by sebasmurphy** [comment]
@carlodef, thanks for the clarification. 

Is there code included in the project to merge all of the outputs after the multiple runs have completed? Or is this something that you achieved in matlab or a similar tool after the fact. The paper linked seems to imply that this is already part of the process.

**Comment by carlodef** [comment]
Hi @sebasmurphy. Sorry for the long delay. The code to merge the outputs after the multiple `s2p` runs have completed is not included in this repository. However, a frozen copy of the code that we used for the IARPA MVS3D challenge is available as a docker image, including the (now outdated) version of `s2p` used at that time and the code to merge the multiple `s2p` outputs: https://hub.docker.com/r/carlodef/s2p-iarpa/

**Comment by sebasmurphy** [comment]
@carlodef Thanks, I'll check it out when I get a chance.

**Comment by gfacciol** [comment]
I'm closing this issue, but don't hesitate to reopen it if you have any problem.
