### ISSUE TITLE
multiprocessing.context.TimeoutError

### ISSUE THREAD

**Issue by yueluming** [cmla/s2p#69]
I use a config.json as follows:

  "roi" : {
      "x" : 6000,
      "y" : 6000,
      "w" : 6000,
      "h" : 6000
  },
  "horizontal_margin": 20,
  "vertical_margin": 5,
  "tile_size" : 2500,
  "disp_range_method" : "sift",
  "msk_erosion": 0,
  "dsm_resolution": 5

But it has this error:
running stereo matching...
Traceback (most recent call last):
  File "/home/Desktop/S2P/s2p/s2p/__init__.py", line 662, in <module>
    main(file)
  File "/home/Desktop/S2P/s2p/s2p/__init__.py", line 568, in main
    timeout=timeout)
  File "/home/Desktop/S2P/s2p/s2p/parallel.py", line 102, in launch_calls
    outputs.append(r.get(timeout))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 640, in get
    raise TimeoutError
multiprocessing.context.TimeoutError

Process finished with exit code 1

**Comment by gfacciol** [comment]
The tile size you are using is too large.
Try setting: 
"tile_size" : 500,
or
"tile_size" : 1000,

**Comment by yueluming** [comment]
> The tile size you are using is too large.
> Try setting:
> "tile_size" : 500,
> or
> "tile_size" : 1000,

Thank you very much!
