### ISSUE TITLE
When the input image reaches 10000*10000 pixels, running S2P will throw a timeout exception

### ISSUE THREAD

**Issue by zongchengzuo** [cmla/s2p#75]
I found that if the input image area is 3000 3000 pixels, S2P can successfully generate DSM, but if the input ROI area reaches 10000 10000 pixels, S2P will throw a timeout exception during operation.
Is there any workaround to run a large ROI? Thanks.

```
discarding masked tiles...
done 100 / 100 tiles
Elapsed time: 0:00:07.709964

correcting pointing locally...
done 100 / 100 tiles
Elapsed time: 0:03:49.611596

correcting pointing globally...
Elapsed time: 0:00:00.045189

rectifying tiles...
done 100 / 100 tiles
Elapsed time: 0:00:58.339316

running stereo matching...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/jason/.local/lib/python3.6/site-packages/s2p/parallel.py", line 43, in tilewise_wrapper
    out = fun(*args)
  File "/home/jason/.local/lib/python3.6/site-packages/s2p/__init__.py", line 205, in stereo_matching
    disp_max)
  File "/home/jason/.local/lib/python3.6/site-packages/s2p/block_matching.py", line 182, in compute_disparity_map
    timeout=timeout,
  File "/home/jason/.local/lib/python3.6/site-packages/s2p/common.py", line 93, in run
    env=env, timeout=timeout, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)

subprocess.CalledProcessError: Command '['mgm', '-r', '-1021', '-R', '617', '-s', 'vfit', '-t', 'census', '-O', '8', '-confidence_consensusL', '/home/jason/Desktop/s2pTestData/outputpairGrid9000/tiles/row_0001000_height_1000/col_0008000_width_1000/pair_1/rectified_disp_confidence.tif', '/home/jason/Desktop/s2pTestData/outputpairGrid9000/tiles/row_0001000_height_1000/col_0008000_width_1000/pair_1/rectified_ref.tif', '/home/jason/Desktop/s2pTestData/outputpairGrid9000/tiles/row_0001000_height_1000/col_0008000_width_1000/pair_1/rectified_sec.tif', '/home/jason/Desktop/s2pTestData/outputpairGrid9000/tiles/row_0001000_height_1000/col_0008000_width_1000/pair_1/rectified_disp.tif']' died with <Signals.SIGKILL: 9>.
"""
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jason/.local/bin/s2p", line 11, in <module>
    sys.exit(main())
  File "/home/jason/.local/lib/python3.6/site-packages/s2p/cli.py", line 22, in main
    s2p.main(user_cfg)
  File "/home/jason/.local/lib/python3.6/site-packages/s2p/__init__.py", line 607, in main
    parallel.launch_calls(stereo_matching, tiles_pairs, nb_workers)
  File "/home/jason/.local/lib/python3.6/site-packages/s2p/parallel.py", line 100, in launch_calls
    outputs.append(r.get(600))  # wait at most 10 min per call
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value

subprocess.CalledProcessError: Command '['mgm', '-r', '-1021', '-R', '617', '-s', 'vfit', '-t', 'census', '-O', '8', '-confidence_consensusL', '/home/jason/Desktop/s2pTestData/outputpairGrid9000/tiles/row_0001000_height_1000/col_0008000_width_1000/pair_1/rectified_disp_confidence.tif', '/home/jason/Desktop/s2pTestData/outputpairGrid9000/tiles/row_0001000_height_1000/col_0008000_width_1000/pair_1/rectified_ref.tif', '/home/jason/Desktop/s2pTestData/outputpairGrid9000/tiles/row_0001000_height_1000/col_0008000_width_1000/pair_1/rectified_sec.tif', '/home/jason/Desktop/s2pTestData/outputpairGrid9000/tiles/row_0001000_height_1000/col_0008000_width_1000/pair_1/rectified_disp.tif']' died with <Signals.SIGKILL: 9>.
```

**Comment by lionlai1989** [comment]
I reckon it is the out-of-memory error. Use one of the following command to check.
```
grep -i 'killed process' /var/log/messages  
dmesg | egrep -i 'killed process'  
grep "Killed process" /var/log/syslog```

**Comment by drzhouq** [comment]
it's timeout issue. In the config.jso, @zongchengzuo needs to specify the mgm_timeout parameter. If it is not set, it will be default to 600, which is 10 minutes. From the error message, mgm error out after reach the 10 minutes constraint.

**Comment by gfacciol** [comment]
I agree with @drzhouq, it's a timeout. 
From the log I can say that, for that one tile, the estimated range of disparity has gotten out of control 
>      Command  '['mgm', '-r', '-1021', '-R', '617', .... 

`-r -1021 -R 617`  are the minimum and maximum disparities, so 1639 disparity levels are considered, which is too much by any standard.

You can try using the multiscale mgm matcher
>       "matching_algorithm": "mgm_multi",
it should reduce the range on the areas that are well matched. 
There are also options to restrict the disparity or altitude ranges: 
https://github.com/cmla/s2p/blob/4585eaf783be0d732ec15bdedc54e5e674af2e9a/s2p/config.py#L99

**Comment by drzhouq** [comment]
@gfacciol many thanks. really appreciate your time and help. To use s2p well, one needs to study quite a bit. :-)

**Comment by gfacciol** [comment]
@drzhouq you are right, preparing a manual has been sitting in our backlog for a while now. 
Nevertheless, the main concepts used in the pipeline are described in this tutorial:  https://gfacciol.github.io/IS18/

**Comment by drzhouq** [comment]
understand @gfacciol it takes time and resource to do that. We will consider support you if we use s2p for any work that makes revenue.

**Comment by gfacciol** [comment]
thanks!
